### PR TITLE
Feature/naive_pnl 

### PR DESCRIPTION
**Pull request by Ksteeds**
Refactoring of code - task still incomplete.

### CODE REVIEW

**Comment by Ksteeds** [comment]
Tied to respective issue.

**Comment by Ksteeds** [comment]
Integration of long-only position complete. Requires testing.

**Comment by Ksteeds** [comment]
Further testing required.

**Comment by Ksteeds** [comment]
Refactoring complete.

**Review by rsueppel — APPROVED** [review]

**Pull request merged**
