### PR TITLE
Category_Relations

### PR DESCRIPTION
**Pull request by Ksteeds**
Graphical changes. Multiple coefficient boxes.

### CODE REVIEW

**Comment by Ksteeds** [comment]
Moving onto the second task.

**Comment by Ksteeds** [comment]
2nd task complete - connecting the associated issue.

**Comment by Ksteeds** [comment]
Minor change to the title format.

**Comment by Ksteeds** [comment]
RegScatter addressed.

**Comment by Ksteeds** [comment]
Colour matching required.

**Review by rsueppel — APPROVED** [review]

**Pull request merged**
