### PR TITLE
Batch tracking mechanism modified.

### PR DESCRIPTION
**Pull request by Ksteeds**
Believe the code is complete. Testing the algorithm at the moment.

### CODE REVIEW

**Comment by Ksteeds** [comment]
Requires further work tomorrow.

**Comment by Ksteeds** [comment]
Will aim to implement Queue solution to provide further control over the thread workflow.

**Comment by Ksteeds** [comment]
Switching branch to trial new algorithm.

**Comment by Ksteeds** [comment]
New algorithm complete.

**Review by lsimonsen — APPROVED** [review]

**Pull request merged**
