### PR TITLE
target_positions(), make_zn_scores() & category_relations().

### PR DESCRIPTION
**Pull request by Ksteeds**
Work-in-progress.

### CODE REVIEW

**Comment by Ksteeds** [comment]
Modularised the main driver function to test thoroughly the logic.

**Comment by Ksteeds** [comment]
Required changing historic_vol.py file, and will require potentially additional work on the associated Unit Test.

**Comment by Ksteeds** [comment]
First method required for the Unit Test and then it should subsequently be complete.

**Comment by Ksteeds** [comment]
Believe the Unit Test is complete - the final method might require some more value testing.

**Review by rsueppel — APPROVED** [review]

**Comment by Ksteeds** [comment]
Multiple pull requests merged into a single request.

**Comment by Ksteeds** [comment]
Excluded the work on dq.py.

**Review by rsueppel — APPROVED** [review]

**Pull request merged**
